### ISSUE TITLE
Feedback Request #1: Engineering Artefacts

### ISSUE THREAD

**Issue by csirostu** [ConsumerDataStandardsAustralia/engineering#25]
### Hypothesis
The Engineering working group should develop a Conformance Test Suite, Java Client Library and Server Stubs and a Desktop Sandbox.
### Description
The Data Standards Body, specifically the Engineering stream, should develop a set of software artefacts to enable the adoption of the Consumer Data Standards as follows:

1. _Conformance_: Enable verification that participants are technical compliant
2. _Reference Implementations_: Development of a Java Client Library and Java Server Stubs
3. _Desktop Sandbox_: A standalone simulation of the Consumer Data Standards ecosystem to enable new participants to rapidly discover and build minimum viable products demonstrating their business ideas.

The Engineering Working Group currently prefers the **Inhouse Development** option.

### Available Options
A number of implementation options have been considered at length. These are summarised as follows.

**Inhouse Development (Currently Preferred)**

The DSB undertakes to develop internally and release under MIT license the following:

- Conformance Test Suite
- Reference Implementations, specifically, a Java Client Library and Java Server Stub
- Desktop Sandbox

As an innovation kickstarter, this is essentially “batteries included” with the license encouraging commercial solution development that embraces the artefacts.

**Pros:**

- Data Standards Body can now clearly demonstrate the Standards definition
- Variation in implementation is reduced
- Timelines can be managed internally for delivery

**Cons:**

- Requires DSB and subsequently the ACCC to commit to ongoing maintenance

**Develop Nothing**
Limit the scope of the Data Standards Body to the production of API Definitions (Standards Working Group), Security Profiles (InfoSec Working Group) and CX Guidelines (CX Working Group). Rely on industry to implement the proposed standards. At a high level this was the initial approach taken by the UK Open Banking (OBIE) project.

**Pros:**

- Significant reduction in resourcing requirements for the Data Standards Body
- Likely completion ahead of schedule for the Data Standards Body at the expense of a longer timeline for the scheme as a whole

**Cons:**

- No independent demonstration of the Standards
- _(UK Observation)_ Potential for significant differences in functional and security implementations
- _(UK Observation)_ Does not define a rigid structure against which Data Holders can be sufficiently tested against
- _(UK Observation)_ Results in Data Recipients being forced to test Data Holders consuming significant the often limited time and money these organisations have
- _(UK Observation)_ Divergences cause Data Recipients to reverse engineer solutions (“screen scraping”) outside of the scheme impacting security and reliability of the services they provide

**Market Build**
The Data Standards Body defines a set of deliverables and contracts individual FinTech partners to deliver on these objectives. The deliverables themselves are completed as a commercial engagement with shared intellectual property rights. 

**Pros:**

- Access to more resources results in concurrent delivery
- Data Standards Body responsibility is limited to project management

**Cons:**

- Perception of bias in the market for unsuccessful FinTech’s
- Delay to initial functional testing - multiple projects in train will introduce project delays
- Open Source contribution (under various licenses) but potential for significant monetary impact to the Data Standards Body
- _(UK Observation)_ Fintech’s have “paid the price” providing “free” testing services to Data Holders without unified implementations. It is questionable the Australian market could do the same.
- _(UK Observation)_ Building frustration from Fintech’s has resulted in regulatory friction including within PSD2, “screen scraping” and GDPR policy frameworks
- _(UK Observation)_ FinTech’s are discovering that Data Holders have better APIs and higher reliability on their internet banking interfaces, in essence, “screen scraping 2.0”

**Comment by csirostu** [comment]
Reserving first post for thread summary.

**Comment by dspeirsy** [comment]
Bravura Solutions preference is option 1. Im certain participants would be prepared to pay a licence\maintenance to fund ongoing support. Apologies if this is not the correct forum for feedback. Darren
