### ISSUE TITLE
Feedback Request #2: Shared Definition Approach

### ISSUE THREAD

**Issue by csirostu** [ConsumerDataStandardsAustralia/engineering#26]
### Hypothesis
Developing software artefacts with a compilable model in Java (cds-models) ensures long term sustainability within the Engineering outputs produced by the Data Standards Body.

### Description
The Data Standards Body, specifically the Engineering stream, have an ongoing objective to provide software artefacts which enable verification that participants are technical compliant (“Conformance”), enable new participants within the scheme to efficiently build solutions utilising the Standards (“Client Libraries”) while providing examples of how a Data Holder can implement the Standards (“Server Stubs”).

All of these rely on a shared and suitably accurate description of how data is exchanged between participants and this requires the “wrapping up” into a “shared library” capability to ensure consistency of the resultant artefacts.

Finally, the Data Standards Body has an imperative to kickstart the local ecosystem around the emerging Standards and therefore must consider timeline constraints.

The Engineering Working Group currently preferences **Java Models**.

### Available Options
Within the Data61 Consumer Data Standards team a number of alternatives have been discussed at length. A high level summary of these alternatives is discussed below, this has been deliberately limited in brevity to provide a reasonable summary of considerations.

**Java Models (Currently Preferred)**
This proposal was outlined in depth within the [Engineering Workshop #1](https://consumerdatastandardsaustralia.github.io/engineering/_static/workshop1.pdf) (slides 30-36).

As initial work has begun ([Sprint #1](https://consumerdatastandardsaustralia.github.io/engineering/sprints/sprint1.html#)) the following is a high level definition of initial approach:

- Implementation of a set of Java Models which are leveraged by supporting tools output by the Engineering Working Group
- Initial focus on a generator for swagger.json from these models which allows for:
- Verification of the supplied swagger definitions from Standards Working Group
- Industry access to a rigidly defined swagger definition for use within their own vendor tools

**Pros:**

- Programmatic definition of the Standards
- Existing exposure to Swagger-core and Swagger-codegen allows for adoption of some existing implementation patterns
- Integration with swagger-core allows a “perfectly” compliant swagger.json generation
- Flexibility to produce multiple API definition formats
- Specific constraints can be defined as accurately as the output format allows
- Java based implementation results in a significant pool of technical resources

**Cons:**

- Requires Java knowledge to read and modify
- Requires DSB to commit to ongoing maintenance

**Swagger-codegen + Vendor Extensions**
Using the Standards Working Group supplied swagger.json combined with industry tooling, notably swagger-codegen (native or forked). Supplement this initial generation with either hand coded modification or potentially multiple template options.

**Pros:**

- Consistent use of Industry tooling
- “Speed to market” due to the existing code base

**Cons:**

- Very limited support for ongoing versioning (“snapshot in time” versus “versioned models”) will likely result in potential for client library classpath poisoning
- Hand modification of generated source code is required
- Limited fidelity with respect to data types
- No support of the proposed authentication and authorisation schemes
- Limited ability to commit upstream changes due to vendor specific options
- Locked into a specific version of OpenAPI (swagger/OpenAPI2)
- Conditionality (anyOf/allOf/not/oneOf) not available within OpenAPI2
- Test case generation not implicitly available, effort likely significant to meet Conformance requirements

**Modified swagger definition + Vendor Extensions**
Modify the defined swagger.json to be technically non-conformant but expressive enough to meet the requirements of the Consumer Data Standards. Modify swagger-codegen to parse and generate from this definition.

**Pros:**

- All use cases can technically be covered (by continuing to extend the definition)
- Versioning can be established allowing rolling version support

**Cons:**

- Likely to have an impact on implementation timelines with diminishing returns as changes become more challenging (“technical debt”)
- Proprietary format that is neither Swagger nor Java in nature. Not vendor parseable & requires specific domain knowledge to understand.
- Modifications to swagger-codegen are likely significant and represent a diminishing return (ie. increasing technical debt for less benefit over time)
- Upgrades to alternative API definition formats (OpenAPI3/gRPC etc) will likely result in a large scale reengineering effort to facilitate

**Use of a Domain Specific Language (DSL)**
Using a standardised tool such as ANTLR (https://www.antlr.org/) define a Domain Specific Language that enables extensibility without enforcing code based definition (ie. Java).

**Pros:**

- All use cases can be covered
- Versioning can be enabled
- Simplest method of proposing new changes
- Probably the strongest typing available when defining the Standards

**Cons:**

- Significant increase during implementation for both Engineering and Standards working groups
- Increased ongoing maintenance overhead
- Likely significant delays in timely delivery of usable assets
- Requires domain specific knowledge to understand

**Comment by csirostu** [comment]
Reserving first post for thread summary.

**Comment by dspeirsy** [comment]
Bravura Solutions supports option 1. Kind regards Darren
