### ISSUE TITLE
Engineering Artefacts Feedback Thread

### ISSUE THREAD

**Issue by anzbankau** [ConsumerDataStandardsAustralia/engineering#41]
Hi @csirostu ,

Not sure if this is how you want feedback captured, so feel free to move wherever is more appropriate. 

Please find below some feedback for the Conformance Test Suite:

- The swagger definitions used by the current conformance test suite are not aligned with standards release as on 8th May.
- The failure report should provide more detailed information on causes of failures, including expected and actual values, data paths etc (from calls we understand this is a backlog item).
- An exportable execution report (e.g. HTML) with details indicating the version of the conformance suite, version of swagger definitions, would help in tracking and storing the results.

Thanks

**Comment by csirostu** [comment]
Hi @anzbankau ,

You have come to the right place. What you've raised is totally valid and also in progress at the moment.

Specifically related to the alignment with the Standards, we agree, we have not yet realigned yet but do intend to do this as part of this weeks sprint.

Thanks for your feedback, much appreciated, keep it coming. Will leave this thread open for others to add further feedback and ask @fyang1024 to mention this issue when posting commits that are related.

**Comment by csirostu** [comment]
Adding private relayed feedback:
- Fields with type AmountString validate even if there is an incorrect number of significant digits after the decimal point. For example both “4” and “4.00” validate, but a minimum of two digits is required in the standard.
- For BankingProductFee at least one of amount, balanceRate, transactionRate and accruedRate is mandatory, but this isn’t checked.

**Comment by spikejump** [comment]
Hi @csirostu,

Tried to run one of the docker image on a Linux VM but the image is not starting up due to the following error:

`docker run -it consumerdatastandardsaustralia/cds-client-java-cli:0.0.2-SNAPSHOT
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/usr/bin/java\": stat /usr/bin/java: no such file or directory": unknown.`

The VM has java and the stat is fine.  Any ideas?

Thanks.

**Comment by csirostu** [comment]
Hi @spikejump,

Yes, this is an identified issue originally by @rickos-aws in ConsumerDataStandardsAustralia/cds-holder-java-spring#3. I've posted a workaround there and we will wrap this up in our next release following Sprint #6.

Thankyou for testing our artefacts, any and all feedback welcome.

Thanks,

Stuart

**Comment by csirostu** [comment]
A few updates on reports so far:
> The swagger definitions used by the current conformance test suite are not aligned with standards release as on 8th May.

``cds-models`` 0.9.3-SNAPSHOT has now been updated to the Standards release in ``sprint-6`` branch. We are working on realignment of ``cds-codegen`` with these changes so they flow through to the other assets.

> * Fields with type AmountString validate even if there is an incorrect number of significant digits after the decimal point. For example both “4” and “4.00” validate, but a minimum of two digits is required in the standard.

This has been rectified in ``cds-models`` 0.9.3-SNAPSHOT. I'll admit when I wrote these regex's I did them blind so I've been a bit surprised only one had problems. Have formally checked them now and I think it will suffice for now but interested in third-party verification.

> * For BankingProductFee at least one of amount, balanceRate, transactionRate and accruedRate is mandatory, but this isn’t checked.

Yes, this is on account of ``oneOf`` not being supported in our initial artefacts. We have now introduced ``oneOf`` in ``cds-models`` 0.9.3-SNAPSHOT and are progressing with integrating it into downstream artefacts.

The following items are still pending but yes, we do intend to address them this sprint @anzbankau:
>The failure report should provide more detailed information on causes of failures, including expected and actual values, data paths etc (from calls we understand this is a backlog item).
>An exportable execution report (e.g. HTML) with details indicating the version of the conformance suite, version of swagger definitions, would help in tracking and storing the results.

Thanks again for the feedback, keep it coming. :)

**Comment by csirostu** [comment]
Further update on these:

> For BankingProductFee at least one of amount, balanceRate, transactionRate and accruedRate is mandatory, but this isn’t checked.

Clarity has been provided this is not a ``oneOf`` but rather an ``anyOf`` requiring one or more of the values to be checked. Conformance now enforces this along with a series of business rules associated within ``additionalValue``.

> The failure report should provide more detailed information on causes of failures, including expected and actual values, data paths etc (from calls we understand this is a backlog item).
> An exportable execution report (e.g. HTML) with details indicating the version of the conformance suite, version of swagger definitions, would help in tracking and storing the results.

@anzbankau We are building on Serenity BDD within Conformance and this should provide detailed information. This provides a HTML Report and we will endeavour to have CDS specific versions injected at the start of it.

**Comment by csirostu** [comment]
**Pending more formal feedback thread**

> > For BankingProductFee at least one of amount, balanceRate, transactionRate and accruedRate is mandatory, but this isn’t checked. Clarity has been provided this is not a `oneOf` but rather an `anyOf` requiring one or more of the values to be checked. Conformance now enforces this along with a series of business rules associated within `additionalValue`.

This is now released in 0.9.3-SNAPSHOT assets. 

> @anzbankau We are building on Serenity BDD within Conformance and this should provide detailed information. This provides a HTML Report and we will endeavour to have CDS specific versions injected at the start of it.

@anzbankau @spikejump 

I'll cover more of this in the material tomorrow (which we'll hopefully record for review) but for observers, early release of draft workshop material (which includes commands in footers) attached.
[Engineering Workshop #2.pdf](https://github.com/ConsumerDataStandardsAustralia/engineering/files/3281816/Engineering.Workshop.2.-.CDS.Branding.1.pdf)

Included in this is Serenity BDD based HTML reporting and a product summariser. Still tweaking the "nice" formatting elements and a more formal feedback thread will be opened soon.

Thanks,

Stuart
