### ISSUE TITLE
MaskedAccountString - conformance tests validate based on example formats from data standards.

### ISSUE THREAD

**Issue by anzbankau** [ConsumerDataStandardsAustralia/engineering#53]
Hi,

A issue we've found with the conformance testing suite is for fields using the common field type MaskedAccountString – the conformance tests currently fail if the format is not either:
• "xxxx xxxx xxxx 1234"
• "xxx-xxx xxxxx1234"

However the above are just example formats, and account numbers will validly have different lengths/formats to this. Instead the conformance testing should focus on the format description - _all digits except the last four replaced with a lowercase x_.

We anticipate a similar issue would exist for MaskedPANString.

Thanks.

**Comment by nghamilton** [comment]
Thank you for raising this issue. It appears that this is a question of interpretation of the Standards, and there is significant ambiguity on how they could be interpreted. @kirky61 will comment and make any necessary changes to the Standards documentation.

**Comment by nghamilton** [comment]
The Standard's team (@kirky61 ) have confirmed that the MaskedAccountString should be any number of `x`s interspersed by any characters suitable for the display of the account number (including but not limited to ` ` and `-`), with the final 4 digits left unmasked.

**Comment by fyang1024** [comment]
> The Standard's team (@kirky61 ) have confirmed that the MaskedAccountString should be any number of `x`s interspersed by any characters suitable for the display of the account number (including but not limited to ` ` and `-`), with the final 4 digits left unmasked.

what are the characters suitable for the display of account number, apart from ` ` and `-`?

**Comment by fyang1024** [comment]
Would `------` be deemed suitable? Would `                 ` be deemed suitable?

**Comment by nghamilton** [comment]
Given that the DHs have the option (according to the spec) to send through the masked string based on how it is formatted for their display purposes, this leaves the formatting entirely up to the DH to decide. Our test will have to support any character except for a number as a 'display character', including `-----`.

**Comment by fyang1024** [comment]
ok, so basically `abc1234` is a valid MaskedAccount.

**Comment by kirky61** [comment]
After further consideration and reading through the DP on this I believe from a conformance point of view, the only check that needs to be made is that the string contains 4 numbers, if present. 

I also believe the language on this needs to be updated removing the word "Should" from the description. I have created an issue on this in staging

**Comment by JamesMBligh** [comment]
Hi folks,  I concur with Brian.  This type is essentially a display string (hence string not number).  There is no intention that the content be parsed for accuracy beyond ensuring that a holder hasn't inadvertently provided a number that isn't masked.  This is why the definition uses should rather than must (although I am supportive of it being more specific in this regard).

The description and non-normative examples are provided to drive consistency for the consumer. 
 Requiring the string to match the non-normative examples would certainly be overly restrictive.

**Comment by fyang1024** [comment]
> Hi folks, I concur with Brian. This type is essentially a display string (hence string not number). There is no intention that the content be parsed for accuracy beyond ensuring that a holder hasn't inadvertently provided a number that isn't masked. This is why the definition uses should rather than must (although I am supportive of it being more specific in this regard).
> 
> The description and non-normative examples are provided to drive consistency for the consumer.
> Requiring the string to match the non-normative examples would certainly be overly restrictive.

Hi James and Brian,

As long as you confirm that strings like  `x1234`, `-5678` are all conforming masked account, I am ok to implement that.

**Comment by kirky61** [comment]
As mentioned its a display string. I don't believe conformance is required beyond previous comments,

**Comment by nghamilton** [comment]
@anzbankau The validation of this field has been changed in the test tools to accept any string as input. This patch is now available in RC5.
